var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Number.parseFloat",function(a){return a||parseFloat},"es6","es3");var Coordinate=function(a,b){this.leftToRight=a;this.frontToBack=b};Coordinate.prototype.getLeftToRight=function(){return this.leftToRight};
Coordinate.prototype.getFrontToBack=function(){return this.frontToBack};Coordinate.prototype.printCoordinate=function(a){return outputLeftToRight(this.getLeftToRight(),a)+"<br>"+outputFrontToBack(this.getFrontToBack(),a)};function createCoordinateFromInput(a,b){return new Coordinate(inputLeftToRight(a),inputFrontToBack(a,b))};var Field=function(){this.fieldType=setFieldType();this.sideType=setSideType();this.hashType=setHashType()};Field.prototype.getFieldType=function(){return this.fieldType};Field.prototype.getSideType=function(){return this.sideType};Field.prototype.getHashType=function(){return this.hashType};function setFieldType(){return parseInt(document.querySelector("input[name=fieldTypeRadio]:checked").value)}
function setSideType(){return parseInt(document.querySelector("input[name=sideNameRadio]:checked").value)}function setHashType(){return parseInt(document.querySelector("input[name=hashNameRadio]:checked").value)};var Input=function(a){this.stepsLR=getStepsLR(a);this.onInOut=getOnInOut(a);this.side=getSide(a);this.yardLine=getYardLine(a);this.stepsFB=getStepsFB(a);this.onInFrontBehind=getOnInFrontBehind(a);this.frontBack=getFrontBack(a);this.hashSideline=getHashSideline(a)},END="e",START="s";function getStepsLR(a){return parseFloat(document.querySelector("#"+a+"LRSteps").value)}function getOnInOut(a){return parseInt(document.querySelector("input[name="+a+"OnInOutRadio]:checked").value)}
function getSide(a){return parseInt(document.querySelector("input[name="+a+"SideRadio]:checked").value)}function getYardLine(a){return parseFloat(document.querySelector("#"+a+"YardLine").value)}function getStepsFB(a){return parseFloat(document.querySelector("#"+a+"FBSteps").value)}function getOnInFrontBehind(a){return parseInt(document.querySelector("input[name="+a+"OnInFrontBehindRadio]:checked").value)}
function getFrontBack(a){return parseInt(document.querySelector("input[name="+a+"FrontBackRadio]:checked").value)}function getHashSideline(a){return parseInt(document.querySelector("input[name="+a+"HashSidelineRadio]:checked").value)}function getCounts(){return parseInt(document.querySelector("#counts").value)}var YARDLINES=[50,45,40,35,30,25,20,15,10,5,0],FRONT_SIDELINE=-42,BACK_SIDELINE=42,NCAA_FRONT_HASH=-10,NCAA_BACK_HASH=10,HS_FRONT_HASH=-14,HS_BACK_HASH=14;
function findYardLine(a){for(var b=0,c=0;c<YARDLINES.length;c++)if(YARDLINES[c]===a){b=c;break}return 8*b}
function inputLeftToRight(a){var b=0;switch(a.onInOut){case 0:b=0==a.side?-findYardLine(a.yardLine):findYardLine(a.yardLine);break;case 1:b=50==a.yardLine?0==a.side?-a.stepsLR:a.stepsLR:0==a.side?-findYardLine(a.yardLine)+a.stepsLR:findYardLine(a.yardLine)-a.stepsLR;break;case 2:b=50==a.yardLine?0==a.side?-a.stepsLR:a.stepsLR:0==a.side?-findYardLine(a.yardLine)-a.stepsLR:findYardLine(a.yardLine)+a.stepsLR}return b}
function inputFrontToBack(a,b){var c=0,d=getProcessedFrontBackReferencePoint(a);if(0==b.getFieldType()){b=HS_FRONT_HASH;var e=HS_BACK_HASH}else b=NCAA_FRONT_HASH,e=NCAA_BACK_HASH;switch(d){case 0:c=processDistanceRelativeToReferencePoint(a,FRONT_SIDELINE);break;case 1:c=processDistanceRelativeToReferencePoint(a,b);break;case 2:c=processDistanceRelativeToReferencePoint(a,e);break;case 3:c=processDistanceRelativeToReferencePoint(a,BACK_SIDELINE)}return c}
function getProcessedFrontBackReferencePoint(a){return 0==a.frontBack&&1==a.hashSideline?0:0==a.frontBack&&0==a.hashSideline?1:1==a.frontBack&&0==a.hashSideline?2:1==a.frontBack&&1==a.hashSideline?3:-1}function processDistanceRelativeToReferencePoint(a,b){return 0==a.onInFrontBehind?b:1==a.onInFrontBehind?b-a.stepsFB:b+a.stepsFB};var STEP_SIZE_REFERENCE=8,YARD_LINE_DISTANCE=8,NO_INTERSECTIONS="No Yard Line Intersections Found";function getDistanceBetweenCoordinates(a,b){var c=a.getLeftToRight();a=a.getFrontToBack();var d=b.getLeftToRight();b=b.getFrontToBack();return Math.sqrt(Math.pow(d-c,2)+Math.pow(b-a,2))}var ROUNDER_GRANULARITY=3;function rounder(a){return Number.parseFloat(a).toFixed(ROUNDER_GRANULARITY)}
function getStepSize(a,b,c){a=getDistanceBetweenCoordinates(a,b)/c;return 0==a?"Hold":rounder(STEP_SIZE_REFERENCE/a)+" to 5"}function getMidSetCoordinate(a,b){var c=(a.getLeftToRight()+b.getLeftToRight())/2;a=(a.getFrontToBack()+b.getFrontToBack())/2;return new Coordinate(c,a)}function cleanUp(a){return 0>a?Math.ceil(a):Math.floor(a)}
function findYardLineIntersections(a,b){var c=[],d=cleanUp(a.getLeftToRight()),e=cleanUp(b.getLeftToRight());if(a.getLeftToRight()==b.getLeftToRight())c.push(NO_INTERSECTIONS);else if(d<e)for(b=d;b<=e;b++)b!=a.getLeftToRight()&&0==b%YARD_LINE_DISTANCE&&c.push(b/YARD_LINE_DISTANCE);else{for(b=e;b<=d;b++)b!=a.getLeftToRight()&&0==b%YARD_LINE_DISTANCE&&c.push(b/YARD_LINE_DISTANCE);c.reverse()}0==c.length&&c.push(NO_INTERSECTIONS);return c}
function getSlopeBetweenCoordinates(a,b){var c=b.getFrontToBack()-a.getFrontToBack();a=b.getLeftToRight()-a.getLeftToRight();return c/a}function findB(a,b){return a.getFrontToBack()-getSlopeBetweenCoordinates(a,b)*a.getLeftToRight()}function findYardLineIntersectionCoordinate(a,b,c){var d=getSlopeBetweenCoordinates(a,b);a=findB(a,b);return new Coordinate(c,d*c+a)}function findCrossCount(a,b,c,d){b=getDistanceBetweenCoordinates(a,b);a=getDistanceBetweenCoordinates(a,c);return d/(b/a)}
function printSide(a,b){return 0==a?"":0==b.getSideType()?0>a?SIDE_TERM_0_SIDE_1_SIDE_2[0]:SIDE_TERM_0_SIDE_1_SIDE_2[1]:1==b.getSideType()?0>a?SIDE_TERM_1_LEFT_RIGHT[0]:SIDE_TERM_1_LEFT_RIGHT[1]:""}
function printYardLineCrossInfo(a,b,c,d){var e=findYardLineIntersections(a,b),h="";if(e[0]==NO_INTERSECTIONS)return e[0];for(var f=0;f<e.length;f++){var g=findYardLineIntersectionCoordinate(a,b,e[f]*YARD_LINE_DISTANCE);g=findCrossCount(a,b,g,c);h+="Cross the "+printSide(e[f],d)+" "+YARDLINES[Math.abs(e[f])]+" Yard Line on count "+rounder(g)+"<br>"}return h};var OUTPUT_STRING_YARD_LINE_NAMES=[50,45,40,35,30,25,20,15,10,5,"Goal Line"],OUTPUT_STRING_FRONT_HASH="Front",OUTPUT_STRING_BACK_HASH="Back",OUTPUT_STRING_HOME_HASH="Home",OUTPUT_STRING_VISITOR_HASH="Visitor",OUTPUT_STRING_SIDE_ONE="Side 1 ",OUTPUT_STRING_SIDE_TWO="Side 2 ",OUTPUT_STRING_SIDE_LEFT="Left ",OUTPUT_STRING_SIDE_RIGHT="Right ";
function outputFrontToBack(a,b){if(0===b.getFieldType()){var c=HS_FRONT_HASH;var d=HS_BACK_HASH}else c=NCAA_FRONT_HASH,d=NCAA_BACK_HASH;if(0===b.getHashType()){b=OUTPUT_STRING_FRONT_HASH;var e=OUTPUT_STRING_BACK_HASH}else b=OUTPUT_STRING_HOME_HASH,e=OUTPUT_STRING_VISITOR_HASH;return 0==a?-c+" behind "+b+" Hash":0>a?a>c?-c+a+" behind "+b+" Hash":a==c?"On "+b+" Hash":a<c&&a>(FRONT_SIDELINE+c)/2?c+-a+" in front of "+b+" Hash":a>FRONT_SIDELINE?-FRONT_SIDELINE+a+" behind "+b+" Sideline":a==FRONT_SIDELINE?
"On "+b+" Sideline":-(a-FRONT_SIDELINE)+" in front of "+b+" Sideline":a<d?d-a+" in front of "+e+" Hash":a==d?"On "+e+" Hash":a>d&&a<(BACK_SIDELINE+d)/2?a-d+" behind "+e+" Hash":a<BACK_SIDELINE?BACK_SIDELINE-a+" in front of "+e+" Sideline":a==BACK_SIDELINE?"On "+e+" Sideline":a-BACK_SIDELINE+" behind "+e+" Sideline"}
function outputLeftToRight(a,b){var c=a%8;if(0===b.getSideType()){b=OUTPUT_STRING_SIDE_ONE;var d=OUTPUT_STRING_SIDE_TWO}else b=OUTPUT_STRING_SIDE_LEFT,d=OUTPUT_STRING_SIDE_RIGHT;0===a?c="On 50":0<a?(a=Math.floor(a/8),c=0===c?"On "+d+OUTPUT_STRING_YARD_LINE_NAMES[a]:4>=c?c+" steps Outside "+d+OUTPUT_STRING_YARD_LINE_NAMES[a]:8-c+" steps Inside "+d+OUTPUT_STRING_YARD_LINE_NAMES[a+1]):(a=Math.ceil(a/8),c=0===c?"On "+b+OUTPUT_STRING_YARD_LINE_NAMES[-a]:-4<=c?-c+" steps Outside "+b+OUTPUT_STRING_YARD_LINE_NAMES[-a]:
8+c+" steps Inside "+b+OUTPUT_STRING_YARD_LINE_NAMES[-a+1]);return c};function init(){initializeSliderLabelValues();startListening();calculateMidsetInformation()}function initializeSliderLabelValues(){resetStartSliders();resetEndSliders();resetCountSlider()}var RANGE_YARDLINE_DEFAULT_VALUE=50,RANGE_STEPS_DEFAULT_VALUE=0,RANGE_COUNTS_DEFAULT_VALUE=8;
function resetInputSliders(a,b,c){a=document.querySelectorAll(a);b=document.querySelectorAll(b);c=document.querySelectorAll(c);setInnerHTMLAndValue(a,RANGE_STEPS_DEFAULT_VALUE);setInnerHTMLAndValue(b,RANGE_YARDLINE_DEFAULT_VALUE);setInnerHTMLAndValue(c,RANGE_STEPS_DEFAULT_VALUE)}function resetStartSliders(){resetInputSliders(RANGE_START_LRSTEPS,RANGE_START_YARDLINE,RANGE_START_FBSTEPS)}function resetEndSliders(){resetInputSliders(RANGE_END_LRSTEPS,RANGE_END_YARDLINE,RANGE_END_FBSTEPS)}
function resetCountSlider(){var a=document.querySelectorAll(RANGE_COUNTS_SLIDER);setInnerHTMLAndValue(a,RANGE_COUNTS_DEFAULT_VALUE)}function setInnerHTMLAndValue(a,b){a[0].innerHTML=b;a[1].value=b}
var RANGE_START_LRSTEPS=".startLRSteps",RANGE_START_YARDLINE=".startYardLine",RANGE_START_FBSTEPS=".startFBSteps",RANGE_END_LRSTEPS=".endLRSteps",RANGE_END_YARDLINE=".endYardLine",RANGE_END_FBSTEPS=".endFBSteps",RANGE_COUNTS_SLIDER=".countsSlider",HASH_TERM_0_FRONT_BACK=["Front","Back"],HASH_TERM_1_HOME_VISITOR=["Home","Visitor"],SIDE_TERM_0_SIDE_1_SIDE_2=["Side 1","Side 2"],SIDE_TERM_1_LEFT_RIGHT=["Left","Right"],HASH="hash",SIDE="side";
function startListening(){document.addEventListener("input",function(a){a.target.matches(RANGE_START_LRSTEPS)&&(document.querySelector(RANGE_START_LRSTEPS).innerHTML=a.target.value);a.target.matches(RANGE_START_YARDLINE)&&(document.querySelector(RANGE_START_YARDLINE).innerHTML=a.target.value);a.target.matches(RANGE_START_FBSTEPS)&&(document.querySelector(RANGE_START_FBSTEPS).innerHTML=a.target.value);a.target.matches(RANGE_END_LRSTEPS)&&(document.querySelector(RANGE_END_LRSTEPS).innerHTML=a.target.value);
a.target.matches(RANGE_END_YARDLINE)&&(document.querySelector(RANGE_END_YARDLINE).innerHTML=a.target.value);a.target.matches(RANGE_END_FBSTEPS)&&(document.querySelector(RANGE_END_FBSTEPS).innerHTML=a.target.value);a.target.matches(RANGE_COUNTS_SLIDER)&&(document.querySelector(RANGE_COUNTS_SLIDER).innerHTML=a.target.value)},!1);document.addEventListener("click",function(a){a.target.matches(".nightRadio")&&lightsOff();a.target.matches(".dayRadio")&&lightsOn();a.target.matches(".hashFrontBack")&&updateTerminology(HASH_TERM_0_FRONT_BACK,
HASH);a.target.matches(".hashHomeVisitor")&&updateTerminology(HASH_TERM_1_HOME_VISITOR,HASH);a.target.matches(".sideOneTwo")&&updateTerminology(SIDE_TERM_0_SIDE_1_SIDE_2,SIDE);a.target.matches(".sideLeftRight")&&updateTerminology(SIDE_TERM_1_LEFT_RIGHT,SIDE)},!1)}function lightsOn(){var a=document.querySelector("body");a.classList.contains("night")&&(a.classList.remove("night"),a.classList.add("day"))}
function lightsOff(){var a=document.querySelector("body");a.classList.contains("day")&&(a.classList.remove("day"),a.classList.add("night"))}function updateTerminology(a,b){b=document.querySelectorAll("."+b+"Term");for(var c=0;c<b.length;c++)b[c].innerHTML=a[c%2]}var midsetTextDisplay=document.querySelector(".midset"),stepSizeDisplay=document.querySelector(".step-size"),crossCountDisplay=document.querySelector(".cross-count");
function calculateMidsetInformation(){var a=new Input(START),b=new Input(END),c=new Field;a=createCoordinateFromInput(a,c);b=createCoordinateFromInput(b,c);var d=getMidSetCoordinate(a,b);midsetTextDisplay.innerHTML=d.printCoordinate(c);stepSizeDisplay.innerHTML=getStepSize(a,b,getCounts());crossCountDisplay.innerHTML=printYardLineCrossInfo(a,b,getCounts(),c)}
function copyEndToStart(){var a=new Input(END);setRadioValue("sOnInOutRadio",a.onInOut);copySliderValue(RANGE_START_LRSTEPS,a.stepsLR);copySliderValue(RANGE_START_YARDLINE,a.yardLine);setRadioValue("sSideRadio",a.side);setRadioValue("sOnInFrontBehindRadio",a.onInFrontBehind);copySliderValue(RANGE_START_FBSTEPS,a.stepsFB);setRadioValue("sFrontBackRadio",a.frontBack);setRadioValue("sHashSidelineRadio",a.hashSideline)}
function copySliderValue(a,b){a=document.querySelectorAll(a);a[0].innerHTML=b;a[1].value=b}function setRadioValue(a,b){document.querySelectorAll("."+a)[b].click()}init();
